services:
  - type: web
    name: ocr-app-backend
    runtime: node
    plan: free
    startCommand: node backend/src/server.js
    buildCommand: cd backend && npm install
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    routes:
      - path: /api/v1
        destination: /api/v1
